image: docker:git
services:
  - docker:dind

stages:
  - dockerize_dev
  - dockerize_QA
  - dockerize_PRO

variables:
  i: 1
  j: 0
  k: 0
  tag: ''
  ambiente: $CI_COMMIT_REF_SLUG
  
before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
  - docker manifest inspect registry.gitlab.com/piramide-portal-3601/intranetsegurospiramide:dev-1.0.8
  - chmod +x ./tag_image.sh 
  - ./tag_image.sh 


Dockerize_dev:
  stage: dockerize_dev
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:test-1.0.8 .
    - docker push $CI_REGISTRY_IMAGE:test-1.0.8
  only:
    - develop

Dockerize_QA:
  stage: dockerize_QA
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:qa-$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:qa-$CI_COMMIT_REF_SLUG
  only:
    - quality


Dockerize_PRO:
  stage: dockerize_PRO
  script:
    - docker build --pull -t CI_COMMIT_TAG:prod-$CI_COMMIT_TAG .
    - docker push CI_COMMIT_TAG:prod-$CI_COMMIT_TAG
  only:
    - main

